### ISSUE TITLE
Fonts

### ISSUE THREAD

**Issue by gregmax17** [SpringRoll/Springroll-Seed#5]
How can fonts be loaded via CSS?

**Comment by SmithAF** [comment]
I apparently didn't add the rule to handle fonts but once #6 gets merged in you will just be able to add fonts using the relative path like so in the css
```css
@font-face {
  font-family: "MyWebFont";
  src: url("./myfont.otf") format("opentype");
}
```
